import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube } from 'react-icons/ai';
import Image from "next/image";
import junbin from 'public/JunBin.png';
import 'src/pages/index.js';
import web1 from 'public/web1.png';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Tan Jun Bin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 '>
        {/* Page 1  intro*/}
        <section className="mb-32">
           <nav className='py-10 mb-12 flex justify-between'>
              <h1 className='text-xl'>developedbyjunbin</h1>
              <ul className='flex items-center'>
                <li>
                  <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
                </li>
                <li><a href='#' className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
              </ul>
           </nav>
           <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Tan Jun Bin</h2>
            <h3 className='text-2xl py-2'>Software Engineer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
              Aspiring Software Engineer and product enthusiast with a flair for innovative digital solutions. Dive in to discover my tech journey!
            </p>
           </div>
           <div className='flex text-5xl justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <a href='https://www.linkedin.com/in/tanjunbin/' className='cursor-pointer'>
              <AiFillLinkedin/>
            </a>
            <AiFillYoutube/>
           </div>
           <div className='relative mx-auto mt-10 object-center h-80 w-80 overflow-hidden'>
              <Image src={junbin} className='rounded-full h-80 w-80 object-cover object-top' layout='fill' objectFit='cover'/>
           </div>
        </section>
        {/* Page 2 about */}
        <section className='mb-32'>
          <div className='p-10'>
            <h3 className='text-3xl py-1'>About me</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Hello! I'm Jun Bin, an aspiring Software Engineer specialising in Computing in Information Systems at the National University of Singapore. I've had an exciting journey spanning roles as a <span className='text-teal-500'>Software Engineer at Bitopia Technology</span>, to leading as the <span className='text-teal-500'>Head of Product at Google Developer Student Clubs NUS</span>, 
            and founding <span className='text-teal-500'>/ff</span> — all with an unwavering focus on crafting user-centric digital solutions. 
            </p>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Off-screen, my passions lie in immersing myself in anime, devouring manga, and exploring the world through photography. I'm thrilled to continue my journey towards making technology increasingly accessible and intuitive.
            </p>
          </div>
          
        </section>
        {/* Page 3 Skills and Experince */}
        <section className='mb-32'>
            <div className='p-10'>
              <h3 className='text-3xl py-1'>Skills & Experiences</h3>
              <p></p>
            </div>
        </section>
        {/* Portfolio */}

        <section className='mb-32'>
            <div className='p-10'>
              <h3 className='text-3xl py-1'>Portfolio</h3>
              <div className='text-center shadow-lg  dark:shadow-dark-lg p-10 rounded-xl my-10'> 
                <Image className='mx-auto' src={web1} width={400} height={400}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>WhatGPT3 Website</h3>
                <p className='py-2'>Transforming Figma Design into a Dynamic React Website</p>
                <h4 className='text-teal-600 py-4'>Technology Stack</h4>
                <p className='text-gray-800 py-1'>add the stack here</p>
              </div>

              <div className='text-center shadow-lg  dark:shadow-dark-lg p-10 rounded-xl my-10'> 
                <Image className='mx-auto' src={web1} width={400} height={400}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Website 2</h3>
                <p className='py-2'>Transforming Figma Design into a Dynamic React Website</p>
                <h4 className='text-teal-600 py-4'>Technology Stack</h4>
                <p className='text-gray-800 py-1'>add the stack here</p>
              </div>

              <div className='text-center shadow-lg  dark:shadow-dark-lg p-10 rounded-xl my-10'> 
                <Image className='mx-auto' src={web1} width={400} height={400}/>
                <h3 className='text-lg font-medium pt-8 pb-2'>Website 3</h3>
                <p className='py-2'>Transforming Figma Design into a Dynamic React Website</p>
                <h4 className='text-teal-600 py-4'>Technology Stack</h4>
                <p className='text-gray-800 py-1'>add the stack here</p>
              </div>
            </div>
        </section>

        {/* tester */}
        <section className='mb-32'>
          <div className='p-10'>
            <h3 className='text-3xl py-1'>Pictures of me</h3>
            <p className='text-md py-2 leading-8 text-gray-800'>
            Write somethign here about anime <span className='text-teal-500'>Jojo</span>, to leading as the <span className='text-teal-500'>Head of Product at Google Developer Student Clubs NUS</span>, 
            and founding <span className='text-teal-500'>/ff</span> — all with an unwavering focus on crafting user-centric digital solutions. 
            </p>
          </div>
        </section>

does this show up in github


      </main>
    </div>
  )
}
